sudo: required

services:
  - docker

before_install:
  - docker build -t didoogan/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true didoogan/multi-test npm test

after_success:
  - docker build -t didoogan/multi-client ./client
  - docker build -t didoogan/multi-nginx ./nginx
  - docker build -t didoogan/multi-server ./server
  - docker build -t didoogan/multi-worker ./worker
  # Enter docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push didoogan/multi-client
  - docker push didoogan/multi-nginx
  - docker push didoogan/multi-server
  - docker push didoogan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-462760043757
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


